name: "Update Feeds"

on:
  push:
    branches:
      - main
  schedule:
    -   cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Update Feeds
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Setup dependencies
        run: npm i

      - name: Scan Papers
        run: npx ts-node src/index.ts

      - name: Commit changes
        uses: elstudio/actions-js-build/commit@v4
        with:
          commitMessage: Update Feeds
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUSH_BRANCH: 'main'
